name: stylelinter

on: pull_request

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  phpcs:
    name: stylelinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          persist-credentials: false
      - name: stylelint
        run: |
          npm install
          npx stylelint "**/*.{css,less}" -f github